In [1]:
import pandas as pd

# Series

In [2]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj1 = pd.Series([1,'tariq','numpy','pandas','matplotlib','seaborn','tensorflow','keras','scikit',11.22])

In [4]:
obj1

0             1
1         tariq
2         numpy
3        pandas
4    matplotlib
5       seaborn
6    tensorflow
7         keras
8        scikit
9         11.22
dtype: object

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([2,11,22,75], index=['a','b','c','d'])
print(obj2)

a     2
b    11
c    22
d    75
dtype: int64


In [8]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [9]:
obj2.values

array([ 2, 11, 22, 75])

In [10]:
obj2['a']

2

In [11]:
obj2['b']

11

In [13]:
obj2[['a','b']]

a     2
b    11
dtype: int64

In [14]:
obj2['e'] = 46

In [15]:
obj2

a     2
b    11
c    22
d    75
e    46
dtype: int64

In [17]:
obj2[['a','d','e']]

a     2
d    75
e    46
dtype: int64

In [19]:
obj2[obj2 > 13]

c    22
d    75
e    46
dtype: int64

In [20]:
obj2 * 2

a      4
b     22
c     44
d    150
e     92
dtype: int64

In [21]:
import numpy as np

In [22]:
np.exp(obj2)

a    7.389056e+00
b    5.987414e+04
c    3.584913e+09
d    3.733242e+32
e    9.496119e+19
dtype: float64

In [23]:
np.exp(obj)

0      54.598150
1    1096.633158
2       0.006738
3      20.085537
dtype: float64

In [50]:
obj2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [27]:
'a' in obj2

True

In [28]:
'e' in obj2

True

In [30]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [31]:
obj3 = pd.Series(sdata)

In [32]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [34]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [35]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [36]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [37]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [39]:
print(obj3)
print(obj4)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64


In [40]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [41]:
obj4.name = 'population'
obj4.index.name = 'states'

In [42]:
obj4

states
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [45]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [46]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [47]:
obj['Bob']

4

In [48]:
obj[['Bob','Steve']]

Bob      4
Steve    7
dtype: int64

# DataFrame

In [72]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [52]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [53]:
pd.DataFrame(data, columns = ['state','year','pop'])

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [73]:
frame2 = pd.DataFrame(data, columns = ['state','year','pop','debt'], index = ['one','two','three','four','five','six'])

In [58]:
frame.head()

state  year  pop debt
one      Ohio  2000  1.5  NaN
two      Ohio  2001  1.7  NaN
three    Ohio  2002  3.6  NaN
four   Nevada  2001  2.4  NaN
five   Nevada  2002  2.9  NaN

In [60]:
frame2.columns

Index(['state', 'year', 'pop', 'debt'], dtype='object')

In [61]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [62]:
frame2['pop']

one      1.5
two      1.7
three    3.6
four     2.4
five     2.9
six      3.2
Name: pop, dtype: float64

In [63]:
frame2['debt']

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
six      NaN
Name: debt, dtype: object

In [64]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [65]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [66]:
frame2.head()

state  year  pop debt
one      Ohio  2000  1.5  NaN
two      Ohio  2001  1.7  NaN
three    Ohio  2002  3.6  NaN
four   Nevada  2001  2.4  NaN
five   Nevada  2002  2.9  NaN

In [67]:
frame2.loc['three']

state    Ohio
year     2002
pop       3.6
debt      NaN
Name: three, dtype: object

In [68]:
frame2['debt'] = 11.22

In [69]:
frame2.head()

state  year  pop   debt
one      Ohio  2000  1.5  11.22
two      Ohio  2001  1.7  11.22
three    Ohio  2002  3.6  11.22
four   Nevada  2001  2.4  11.22
five   Nevada  2002  2.9  11.22

In [75]:
frame2['debt'] = np.arange(6.)

In [76]:
frame2.head()

state  year  pop  debt
one      Ohio  2000  1.5   0.0
two      Ohio  2001  1.7   1.0
three    Ohio  2002  3.6   2.0
four   Nevada  2001  2.4   3.0
five   Nevada  2002  2.9   4.0

In [77]:
val = pd.Series([1.4,3.5,5.3], index =['two','four','five'])

In [80]:
frame2['debt'] = val

In [81]:
frame2.head()

state  year  pop  debt
one      Ohio  2000  1.5   NaN
two      Ohio  2001  1.7   1.4
three    Ohio  2002  3.6   NaN
four   Nevada  2001  2.4   3.5
five   Nevada  2002  2.9   5.3

In [82]:
frame2['eastern'] = frame2.state == 'Ohio'

In [83]:
frame2

state  year  pop  debt  eastern
one      Ohio  2000  1.5   NaN     True
two      Ohio  2001  1.7   1.4     True
three    Ohio  2002  3.6   NaN     True
four   Nevada  2001  2.4   3.5    False
five   Nevada  2002  2.9   5.3    False
six    Nevada  2003  3.2   NaN    False

In [84]:
del frame2['eastern']

In [85]:
frame2

state  year  pop  debt
one      Ohio  2000  1.5   NaN
two      Ohio  2001  1.7   1.4
three    Ohio  2002  3.6   NaN
four   Nevada  2001  2.4   3.5
five   Nevada  2002  2.9   5.3
six    Nevada  2003  3.2   NaN

In [86]:
frame2.columns

Index(['state', 'year', 'pop', 'debt'], dtype='object')

In [87]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [88]:
frame3 = pd.DataFrame(pop)

In [89]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [90]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [92]:
pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [93]:
pdata = {'Ohio': frame3['Ohio'][:-1],'Nevada': frame3['Nevada'][:2]}

In [94]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [95]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [97]:
frame3.index.name = 'year'

In [98]:
frame3

Nevada  Ohio
year              
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [99]:
frame3.columns.name = 'state'

In [100]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [101]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [102]:
frame2.values

array([['Ohio', 2000, 1.5, nan],
       ['Ohio', 2001, 1.7, 1.4],
       ['Ohio', 2002, 3.6, nan],
       ['Nevada', 2001, 2.4, 3.5],
       ['Nevada', 2002, 2.9, 5.3],
       ['Nevada', 2003, 3.2, nan]], dtype=object)

In [104]:
arr = np.array([[1,2,3,4],[4,3,2,1],[11,22,2,7]])

In [106]:
frame5 = pd.DataFrame(arr)

In [107]:
frame5

0   1  2  3
0   1   2  3  4
1   4   3  2  1
2  11  22  2  7

In [108]:
arr

array([[ 1,  2,  3,  4],
       [ 4,  3,  2,  1],
       [11, 22,  2,  7]])

In [111]:
d1 = {'a1':np.array([1,2,3,4,5]), 'a2':np.array([6,7,8,9,0]), 'a3':np.array([4,3,6,5,2])}

In [112]:
d1

{'a1': array([1, 2, 3, 4, 5]),
 'a2': array([6, 7, 8, 9, 0]),
 'a3': array([4, 3, 6, 5, 2])}

In [113]:
frame6 = pd.DataFrame(d1)

In [114]:
frame6

a1  a2  a3
0   1   6   4
1   2   7   3
2   3   8   6
3   4   9   5
4   5   0   2

In [115]:
l1 = [1,2,3,4,5]

In [116]:
frame7 = pd.DataFrame(l1)

In [117]:
frame7

0
0  1
1  2
2  3
3  4
4  5

In [118]:
l2 = [[1,2,3,4,5],[1,3,4,5,6],[7,8,9,0,6]]

In [119]:
frame8 = pd.DataFrame(l2)

In [120]:
frame8

0  1  2  3  4
0  1  2  3  4  5
1  1  3  4  5  6
2  7  8  9  0  6

In [121]:
arr2 = np.array([1,2,5,7,9,5])
frame9 = pd.DataFrame(arr2)

In [122]:
frame9

0
0  1
1  2
2  5
3  7
4  9
5  5

In [123]:
t1 = (1,2,3,4,5)
frame10 = pd.DataFrame(t1)
frame10

0
0  1
1  2
2  3
3  4
4  5

In [124]:
t1 = ((1,3,5,3),(3,4,7,5),(0,8,9,7))

In [125]:
frame11 = pd.DataFrame(t1)
frame11

0  1  2  3
0  1  3  5  3
1  3  4  7  5
2  0  8  9  7

In [126]:
d2 = {'c1':(1,4,3,2),'c2':(4,3,6,5),'c3':(7,8,9,0)}
frame12 = pd.DataFrame(d2)
frame12

c1  c2  c3
0   1   4   7
1   4   3   8
2   3   6   9
3   2   5   0

In [127]:
d3 = {'a':{'i':1,'ii':2,'iii':3},'b':{'i':11,'ii':22,'iii':2},'c':{'a':1,'b':2,'c':3}}

In [128]:
frame13 = pd.DataFrame(d3)

In [129]:
frame13

a     b    c
i    1.0  11.0  NaN
ii   2.0  22.0  NaN
iii  3.0   2.0  NaN
a    NaN   NaN  1.0
b    NaN   NaN  2.0
c    NaN   NaN  3.0

In [130]:
l3 = [{'a':1,'b':2,'c':3},{'i':1,'ii':2,'iii':3},{1:'one',2:'two',3:'three'}]

In [131]:
frame14 = pd.DataFrame(l3)

In [132]:
frame14

a    b    c    i   ii  iii    1    2      3
0  1.0  2.0  3.0  NaN  NaN  NaN  NaN  NaN    NaN
1  NaN  NaN  NaN  1.0  2.0  3.0  NaN  NaN    NaN
2  NaN  NaN  NaN  NaN  NaN  NaN  one  two  three

In [133]:
l2

[[1, 2, 3, 4, 5], [1, 3, 4, 5, 6], [7, 8, 9, 0, 6]]

In [134]:
type(l2)

list

In [137]:
frame15 = pd.DataFrame(l2)

In [138]:
frame15

0  1  2  3  4
0  1  2  3  4  5
1  1  3  4  5  6
2  7  8  9  0  6

In [139]:
l3 = [(1,3,4,2),(4,6,7,4),(3,2,4,1)]

In [140]:
frame16 = pd.DataFrame(l3)

In [141]:
frame16

0  1  2  3
0  1  3  4  2
1  4  6  7  4
2  3  2  4  1

In [142]:
frame17 = pd.DataFrame(frame16)

In [143]:
frame17

0  1  2  3
0  1  3  4  2
1  4  6  7  4
2  3  2  4  1

In [144]:
ma = frame17 > 2

In [145]:
ma

0      1     2      3
0  False   True  True  False
1   True   True  True   True
2   True  False  True  False

In [147]:
frame18 = pd.DataFrame(ma)

In [148]:
frame18

0      1     2      3
0  False   True  True  False
1   True   True  True   True
2   True  False  True  False

# Index Objects

In [153]:
s_3 = pd.Series(range(3), index = ['a','b','c'])

In [154]:
s_3

a    0
b    1
c    2
dtype: int64

In [155]:
index = s_3.index

In [156]:
index

Index(['a', 'b', 'c'], dtype='object')

In [157]:
index[1:]

Index(['b', 'c'], dtype='object')

In [158]:
index[1] = 'd'   # index objects are immutable

TypeError: Index does not support mutable operations

In [160]:
labels = pd.Index(np.arange(3))

In [161]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [162]:
s_4 = pd.Series([1.3,4.5,2], index= labels)
s_4

0    1.3
1    4.5
2    2.0
dtype: float64

In [163]:
s_4.index is labels

True

In [164]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [165]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [166]:
'Ohio' in frame3.columns

True

In [167]:
2003 in frame3.index

False

In [168]:
2001 in frame3.index

True

In [169]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [172]:
fi = frame.index

In [173]:
f3i = frame3.index

In [174]:
print(fi)
print(f3i)

RangeIndex(start=0, stop=6, step=1)
Int64Index([2001, 2002, 2000], dtype='int64', name='year')


In [175]:
fi.append(f3i)

Int64Index([0, 1, 2, 3, 4, 5, 2001, 2002, 2000], dtype='int64')

In [179]:
li = [[1,3,4,3],[2,4,6,3],[3,8,6,4]]
frame1 = pd.DataFrame(li)

In [180]:
frame1

0  1  2  3
0  1  3  4  3
1  2  4  6  3
2  3  8  6  4

In [181]:
f1i = frame1.index

In [185]:
print(fi)
print(f1i)

RangeIndex(start=0, stop=6, step=1)
RangeIndex(start=0, stop=3, step=1)


In [184]:
fi.difference(f1i)

Int64Index([3, 4, 5], dtype='int64')

In [186]:
fi.intersection(f1i)

RangeIndex(start=0, stop=3, step=1)

In [187]:
fi.union(f1i)

RangeIndex(start=0, stop=6, step=1)

In [188]:
f1i.isin(fi)

array([ True,  True,  True])

In [189]:
fi.isin(f1i)

array([ True,  True,  True, False, False, False])

In [190]:
fi.delete(f1i)

Int64Index([3, 4, 5], dtype='int64')

In [191]:
fi.drop(f1i)

Int64Index([3, 4, 5], dtype='int64')

In [194]:
f1i

RangeIndex(start=0, stop=3, step=1)

In [195]:
lis = [4,3,2,5,3]
df2 = pd.DataFrame(lis, index=[3,2,5,6,7])

In [196]:
ind = df2.index
ind.delete([0,1])

Int64Index([5, 6, 7], dtype='int64')

In [197]:
ind

Int64Index([3, 2, 5, 6, 7], dtype='int64')

In [198]:
ind

Int64Index([3, 2, 5, 6, 7], dtype='int64')

In [199]:
ind.insert(2,4)

Int64Index([3, 2, 4, 5, 6, 7], dtype='int64')

In [201]:
ind.is_monotonic

False

In [202]:
f1i.is_monotonic

True

In [204]:
ind.is_unique

True

In [205]:
li

[[1, 3, 4, 3], [2, 4, 6, 3], [3, 8, 6, 4]]

In [206]:
lict = [1,2,3]
df_1 = pd.DataFrame(lict, index=[0,0,1])

In [208]:
indexi = df_1.index
indexi.is_unique

False

In [210]:
indexi.unique()

Int64Index([0, 1], dtype='int64')

In [211]:
ind.unique()

Int64Index([3, 2, 5, 6, 7], dtype='int64')

In [212]:
ind

Int64Index([3, 2, 5, 6, 7], dtype='int64')