In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8])

In [3]:
print(arr.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([2,3,4,5])

In [8]:
arr3 = np.concatenate((arr1,arr2))

In [9]:
arr3

array([1, 2, 3, 4, 2, 3, 4, 5])

In [10]:
arr4 = np.concatenate((arr1,arr2), axis=1)

AxisError: ignored

In [11]:
a2d = np.array([[1,2,3],[4,5,6]])
b2d = np.array([[3,2,1],[6,5,4]])

In [12]:
a = np.random.rand(3,4)

In [13]:
a

array([[0.32378747, 0.54175207, 0.62928737, 0.79815195],
       [0.17820136, 0.06923955, 0.12863775, 0.54368308],
       [0.17137606, 0.63060217, 0.92724522, 0.34188895]])

In [14]:
b = np.random.randint(1,100,size=(3,4))

In [15]:
b

array([[18, 15, 33, 47],
       [62, 13, 72, 97],
       [29, 51, 69,  4]])

In [16]:
c = np.random.rand()

In [17]:
c

0.9193383796319167

In [18]:
d = np.random.choice([1,3,2,4,5,6])

In [19]:
d

1

In [20]:
c2d = np.concatenate((a2d,b2d), axis=1)

In [21]:
c2d

array([[1, 2, 3, 3, 2, 1],
       [4, 5, 6, 6, 5, 4]])

In [22]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
b2d

array([[3, 2, 1],
       [6, 5, 4]])

In [24]:
d2d = np.concatenate((a2d,b2d), axis=0)

In [25]:
d2d

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [6, 5, 4]])

In [27]:
arrhs = np.hstack((a2d,b2d))

In [28]:
arrhs

array([[1, 2, 3, 3, 2, 1],
       [4, 5, 6, 6, 5, 4]])

In [29]:
arrvs = np.vstack((a2d,b2d))

In [30]:
arrvs

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [6, 5, 4]])

In [31]:
arrds = np.dstack((a2d,b2d))

In [32]:
arrds

array([[[1, 3],
        [2, 2],
        [3, 1]],

       [[4, 6],
        [5, 5],
        [6, 4]]])

In [33]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])